// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Sfihl3WPjD56aO5ZFc6a7C5ww4RxYmA',
    appId: '1:107542202552:web:b189089afa410ad1198c4d',
    messagingSenderId: '107542202552',
    projectId: 'bootcamp-2f157',
    authDomain: 'bootcamp-2f157.firebaseapp.com',
    storageBucket: 'bootcamp-2f157.appspot.com',
    measurementId: 'G-HM1V76Y5ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_3N12sHwdHWGW334pJ7hHsVEUkwRpaw',
    appId: '1:107542202552:android:514007553b330a3a198c4d',
    messagingSenderId: '107542202552',
    projectId: 'bootcamp-2f157',
    storageBucket: 'bootcamp-2f157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-Epr8HGU0PqO7v9MkdKrDuwJPbVBU78',
    appId: '1:107542202552:ios:783faf5120af004b198c4d',
    messagingSenderId: '107542202552',
    projectId: 'bootcamp-2f157',
    storageBucket: 'bootcamp-2f157.appspot.com',
    androidClientId: '107542202552-eqkjb1lloltdoe1inf988vnmjtla4q4m.apps.googleusercontent.com',
    iosClientId: '107542202552-a6f3ee8rnppmnt9bjrstbql76rtnchu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-Epr8HGU0PqO7v9MkdKrDuwJPbVBU78',
    appId: '1:107542202552:ios:783faf5120af004b198c4d',
    messagingSenderId: '107542202552',
    projectId: 'bootcamp-2f157',
    storageBucket: 'bootcamp-2f157.appspot.com',
    androidClientId: '107542202552-eqkjb1lloltdoe1inf988vnmjtla4q4m.apps.googleusercontent.com',
    iosClientId: '107542202552-a6f3ee8rnppmnt9bjrstbql76rtnchu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcamp',
  );
}
